on: 
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New version to release'     
        required: false
        default: 'warning'
jobs:
  create_tag:
    runs-on: ubuntu-latest
    name: A job to create a tag
    steps:
    - uses: actions/checkout@v2
    - name: Tag creator
      id: tag-creator
      uses: merighifacundo/tag-creator@v1.0.0
      with:
        new-version: ${{ github.event.inputs.newVersion }}
        token: ${{ secrets.GITHUB_TOKEN }}
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
