on: 
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New version to release'     
        required: false
        default: 'warning'
jobs:
  create_tag:
    runs-on: ubuntu-latest
    name: A job to create a tag
    steps:
    - uses: actions/checkout@v2
    - name: Node Version Updater
      id: node-version-updater
      uses: merighifacundo/node-version-updater@v1.0.0
      with:
        new-version: ${{ github.event.inputs.newVersion }}
    - name: Node Release Updater
      id: node-release-updater
      uses: merighifacundo/node-version-creator@v1.2.1
      with:
        new-version: ${{ steps.node-version-updater.outputs.new-version }}
        old-version: ${{ steps.node-version-updater.outputs.old-version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        release-branch: false
        
    # Release Notes
    - name: Release Notes
      run: echo "The time was ${{ steps.node-release-updater.outputs.release-notes }}"
